# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CESNET
#
# oarepo-s3 is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: false

language: python

addons:
  apt:
    packages:
    - rabbitmq-server

services:
  - rabbitmq

matrix:
  fast_finish: true
  allow_failures:
    # To allow failures, you need to specify the full environment
    - env: REQUIREMENTS=devel

cache:
  - pip

env:
  global:
    - ES7_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-linux-x86_64.tar.gz"
    - ES_HOST=127.0.0.1
  matrix:
    - REQUIREMENTS=release DEPLOY=true ES=$ES7_DOWNLOAD_URL
    - REQUIREMENTS=devel ES=$ES7_DOWNLOAD_URL

python:
  - "3.8"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install --upgrade pip==20.2.4 twine wheel coveralls requirements-builder"
  - "requirements-builder -e all --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e all --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e all --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"
  - mkdir /tmp/elasticsearch
  - wget -O - $ES | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - "/tmp/elasticsearch/bin/elasticsearch &"
  - sleep 10
  - "cat .travis-release-requirements.txt"


install:
  - "travis_retry pip install 3rdparty/s3-client"
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"
  - "pip freeze"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "khjYC7NmCt1tTmmGr5wr3I1ccvHC4o/6Tb3lC4610Ke0s1uQ0m9qtu4e6XVb09EGgqfrdzaOH86kJTIx8ksVau3lKepY13APtm9fwXtNM2WfD0UXiEdCrjmLTez0xy4nyRXEAuOfhKPRdQ7Q/ylIpWtKO6jydfIJS3sje1MJ1Cmg/TkS06f7zW4On0i/n7WBq/shs0N9Tha71++sUNRLRBJwfYUd+jHJ6D0EzMDb9dCEjmOPU3nDcnKp8Y0hrbE+F3sSyEha71P3X1hl5mQpSeMTdEsiKyHCvsxhuapbvtGx91Y5xx0HqmlOf78DoTmJIrj0y5Xu3Gtv50VErfQ9NjUfld22hUPO+qU2nd5AKbs5aVaOrN+Z7KeHVBg9x0D7ZDN2kM16mMyyjrGg+/TCRwpYeQIsENvLceaDaG+p/yJgiVlQKAoIhAaOIP3oLwD2jduTeyzdQ/5fqUmJWsslsU9iyAkzvFk67P53UeUKSUaZQ7rcI1F3LOHUlOxKglqQvRuXAWLHCWwJnoCcwzmVYQ+AOM4qRNEDVuiaPYWgKWlMNIn+pMeBxOvjszIZChpsulEuWdn3pwa2xRF1idLw0r4aEeD88GVa5juYaK6X8OFbD8x/9M7z6cfP2JLaWUWL+LCt66YRmzEMqB0tavR2VEbV3L7aI6ZPLAnaMQhtQMQ="
  on:
    tags: true
    branch: "master"
    python: "3.8"
    repo: oarepo/oarepo-s3
    condition: $DEPLOY = true
  distributions: "sdist bdist_wheel"
  skip_existing: true
