# -*- coding: utf-8 -*-
#
# Copyright (C) 2018, 2019, 2020 Esteban J. G. Gabancho.
#
# oarepo-s3 is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true
  allow_failures:
    # To allow failures, you need to specify the full environment
    - env: REQUIREMENTS=devel

cache:
  - pip

env:
  matrix:
    - REQUIREMENTS=release DEPLOY=true
    - REQUIREMENTS=devel

python:
  - "3.8"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e all --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e all --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e all --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install 3rdparty/s3-client"
  - "travis_retry pip install -e .[all]"
  - "pip freeze"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "AZDDkNIYFnHTINqmPPuRDC+X7Hwi92iMBi2DvqsAc2GJ375th+bC70cjJbhysnBwCgMvJGMYtuAxtSrPWLEMIC3kRd7y0X9ZGvRlGlG0M4YhegTfGl9pshwgQL/Jbqz6Ct8O5wAcXloqnUqfCUpWqVtoDiPUnfgW+Nv3rZfpbUJK4/i5S8GVSsk9TCxJECgGvg09RicsgR0pN+sBLLrEYgC1WnNnDB8396oNaGD92BCTLlrwYd9H8TJWe19VsTeVxY9keAkmqXdhv/5y2sypWmXSl1NDvkZUTmCanC+vTnPGsrziAq9OyFr068q3FT5ETdTk6nhWtSElwo0kUWwIAvQ6SbqgI2QOntGvBIf5nbHTsAhPxUU3vr6N7sJmLtKoeLnrQqWFypCoLOsIVCnu6aPNFd/FU+LQdAIFolsQ/RjMZrMn71/K2hKMDVHjiyhxySgXZWOwIc3AplrX1I3a5+PgNwvXueNtXUdDywmgP6DrYSzqEpNbZ9Jj9a172LaMb2uqru1Lc62PCix9omZxM4Zf3eThQUFLftHrtb5mLERtFrt6LSM+hhdNGeNmATasd6RiHiLJZOTmXikNWs9WI79/TmK5bFl3u/HzDsE5XDnPyHcSe9ePEcttrEzORebodOqoqr6MtWevDPYDTmd4aiNdLYlr5ud9V0y+wG+Jh+0="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    branch: "master"
    python: "3.8"
    repo: oarepo/oarepo-s3
    condition: $DEPLOY = true
  distributions: "sdist bdist_wheel"
  skip_existing: true
